# Generated by Django 5.0.3 on 2024-04-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0008_roomcategory_remove_rooms_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_category',
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'Premium'), ('2', 'Deluxe'), ('3', 'Basic')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoomCategory',
        ),
    ]
