# Generated by Django 5.0.3 on 2024-04-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0009_remove_rooms_room_category_rooms_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('premium', 'Premium'), ('deluxe', 'Deluxe'), ('basic', 'Basic'), ('suite', 'Suite'), ('penthouse', 'Penthouse'), ('villa', 'Villa'), ('studio', 'Studio')], max_length=50),
        ),
    ]
