# Generated by Django 5.0.3 on 2024-04-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
