# Generated by Django 5.0.3 on 2024-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sdt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
