# Generated by Django 5.0.3 on 2024-04-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0016_userprofile_sdt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
