# Generated by Django 5.0.4 on 2024-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0020_roomtype_alter_rooms_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='description_room_type',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='type_name',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Not available')], max_length=15),
        ),
    ]
